### ISSUE TITLE
bug: Cannot approve joke

### ISSUE THREAD

**Issue by pitzzahh** [pitzzahh/jokes-API#51]
Stack trace
```java
﻿2023-07-27T15:11:24.670Z ERROR 1 --- [io-8080-exec-36] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [tech.araopj.jokes.submit.entity.JokeRequest@120f102b] did not match expected type [BasicSqmPathSource(id : Integer) ]] with root cause
﻿org.hibernate.type.descriptor.java.CoercionException: Cannot coerce value `tech.araopj.jokes.submit.entity.JokeRequest@120f102b` [tech.araopj.jokes.submit.entity.JokeRequest] as Integer
﻿at org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:188) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:24) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.internal.QueryParameterBindingImpl.coerce(QueryParameterBindingImpl.java:144) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:111) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.spi.AbstractCommonQueryContract.setParameter(AbstractCommonQueryContract.java:949) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.spi.AbstractSelectionQuery.setParameter(AbstractSelectionQuery.java:732) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:1287) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:131) ~[hibernate-core-6.1.6.Final.jar!/:6.1.6.Final]
﻿at org.springframework.data.jpa.repository.query.QueryParameterSetter$BindableQuery.setParameter(QueryParameterSetter.java:337) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.lambda$setParameter$5(QueryParameterSetter.java:130) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.QueryParameterSetter$ErrorHandling$1.execute(QueryParameterSetter.java:143) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.setParameter(QueryParameterSetter.java:130) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.ParameterBinder.bind(ParameterBinder.java:83) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.ParameterBinder.bind(ParameterBinder.java:75) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.ParameterBinder.bindAndPrepare(ParameterBinder.java:97) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.doCreateQuery(AbstractStringBasedJpaQuery.java:107) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createQuery(AbstractJpaQuery.java:234) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.JpaQueryExecution$ModifyingExecution.doExecute(JpaQueryExecution.java:236) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[spring-data-commons-3.0.1.jar!/:3.0.1]
﻿at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.0.1.jar!/:3.0.1]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77) ~[spring-data-commons-3.0.1.jar!/:3.0.1]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.4.jar!/:6.0.4]
﻿at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-6.0.4.jar!/:6.0.4]
﻿at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.4.jar!/:6.0.4]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.4.jar!/:6.0.4]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134) ~[spring-data-jpa-3.0.1.jar!/:3.0.1]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218) ~[spring-aop-6.0.4.jar!/:6.0.4]
﻿at jdk.proxy2/jdk.proxy2.$Proxy108.approveRequest(Unknown Source) ~[na:na]
﻿at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
﻿at tech.araopj.jokes.submit.service.JokeRequestService.approveJoke(JokeRequestService.java:48) ~[classes!/:0.0.2]
﻿at tech.araopj.jokes.submit.controller.JokeRequestController.approveJoke(JokeRequestController.java:56) ~[classes!/:0.0.2]
﻿at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
﻿at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
﻿at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.5.jar!/:na]
﻿at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
﻿at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar!/:na]
﻿at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar!/:na]
﻿at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
﻿at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar!/:na]
﻿at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
```

**Comment by pitzzahh** [comment]
controller method
```java
@RequestMapping("/approve")
public HttpEntity<String> approveJoke(
    @Validated
    @RequestParam("key") String key,
    @Validated
    @RequestParam(name = "joke_id") String id
) {
     if (!Validator.isWholeNumber().test(id)) {
         throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid joke id, must be a number");
     }
     if (!key.equals(decrypt("IVA0c3NXMHJkIQ=="))) {
         throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Invalid key");
     }
     jokeRequestService.approveJoke(Integer.parseInt(id));
     return new HttpEntity<>("Joke approved successfully");
}
```

**Comment by pitzzahh** [comment]
> controller method
> 
> ```java
> @RequestMapping("/approve")
> public HttpEntity<String> approveJoke(
>     @Validated
>     @RequestParam("key") String key,
>     @Validated
>     @RequestParam(name = "joke_id") String id
> ) {
>      if (!Validator.isWholeNumber().test(id)) {
>          throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid joke id, must be a number");
>      }
>      if (!key.equals(decrypt("IVA0c3NXMHJkIQ=="))) {
>          throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Invalid key");
>      }
>      jokeRequestService.approveJoke(Integer.parseInt(id));
>      return new HttpEntity<>("Joke approved successfully");
> }
> ```

poor security :)
